---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip
    - wget

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/travisci/tests.yml -i tests/travisci/inventory --syntax-check
  - wget -O ansible-role-qa https://gist.githubusercontent.com/trombik/047364853d2f8070da9d4f360b4b9da9/raw
  - rvm use 2.1.10
  - ruby ansible-role-qa

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
