---
# tasks file for ansible-role-example

- include_vars: "{{ ansible_os_family }}.yml"

- include: install-FreeBSD.yml
  when: ansible_os_family == 'FreeBSD'

- name: Ensure /tmp/foo exists
  template:
    src: foo.j2
    dest: /tmp/foo
    mode: 0644
