---
# tasks file for ansible-role-example

- name: Include OS specific install task
  include: install-FreeBSD.yml
  when: ansible_os_family == 'FreeBSD'

- name: Ensure /tmp/foo exists
  template: dest='/tmp/foo' src='foo.j2' mode=0644
